<?xml version="1.0" encoding="utf-8"?><Database Name="bitject" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.140.0.3;Initial Catalog=bitject;User ID=bitject" SettingsObjectName="MemberRegister.Properties.Settings" SettingsPropertyName="bitjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.member" Member="member">
    <Type Name="member">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="levelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="companyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="accountTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isApiCreate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="createDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="externalId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nickname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="nationNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="childPid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="childCanViewId" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="loginCountryCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="loginDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="loginCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="loginFailCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="loginIp" Type="System.String" DbType="VarChar(39)" CanBeNull="true" />
      <Column Name="personalId" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="nationCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="sex" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="creditCardInfo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="auth" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="memo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastModifyDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastModifierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="l1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="l2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="l3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="l4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="l5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="l6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="l7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="l8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="l9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reviewStatus" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="industryId" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="feeMode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="feeDividedOwnPercent" Type="System.Decimal" DbType="Decimal(8,4)" CanBeNull="true" />
      <Column Name="feeStackedOwnPercent" Type="System.Decimal" DbType="Decimal(8,4)" CanBeNull="true" />
      <Column Name="score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="registerStatus" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
</Database>