#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithDrawalOrderRequest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bitject")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Insertaccount(account instance);
    partial void Updateaccount(account instance);
    partial void Deleteaccount(account instance);
    partial void InsertaccountTransDetail(accountTransDetail instance);
    partial void UpdateaccountTransDetail(accountTransDetail instance);
    partial void DeleteaccountTransDetail(accountTransDetail instance);
    partial void InsertaccountTrans(accountTrans instance);
    partial void UpdateaccountTrans(accountTrans instance);
    partial void DeleteaccountTrans(accountTrans instance);
    partial void InsertwithdrawalOrder(withdrawalOrder instance);
    partial void UpdatewithdrawalOrder(withdrawalOrder instance);
    partial void DeletewithdrawalOrder(withdrawalOrder instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WithDrawalOrderRequest.Properties.Settings.Default.bitjectConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<account> account
		{
			get
			{
				return this.GetTable<account>();
			}
		}
		
		public System.Data.Linq.Table<accountTransDetail> accountTransDetail
		{
			get
			{
				return this.GetTable<accountTransDetail>();
			}
		}
		
		public System.Data.Linq.Table<accountTrans> accountTrans
		{
			get
			{
				return this.GetTable<accountTrans>();
			}
		}
		
		public System.Data.Linq.Table<withdrawalOrder> withdrawalOrder
		{
			get
			{
				return this.GetTable<withdrawalOrder>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.account")]
	public partial class account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _memberId;
		
		private int _memberLevelId;
		
		private int _memberParentId;
		
		private string _currencyCode;
		
		private decimal _balance;
		
		private decimal _frozenBalance;
		
		private string _status;
		
		private System.DateTime _createDateTime;
		
		private string _memo;
		
		private System.Nullable<int> _l1;
		
		private System.Nullable<int> _l2;
		
		private System.Nullable<int> _l3;
		
		private System.Nullable<int> _l4;
		
		private System.Nullable<int> _l5;
		
		private System.Nullable<int> _l6;
		
		private System.Nullable<int> _l7;
		
		private System.Nullable<int> _l8;
		
		private System.Nullable<int> _l9;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmemberIdChanging(int value);
    partial void OnmemberIdChanged();
    partial void OnmemberLevelIdChanging(int value);
    partial void OnmemberLevelIdChanged();
    partial void OnmemberParentIdChanging(int value);
    partial void OnmemberParentIdChanged();
    partial void OncurrencyCodeChanging(string value);
    partial void OncurrencyCodeChanged();
    partial void OnbalanceChanging(decimal value);
    partial void OnbalanceChanged();
    partial void OnfrozenBalanceChanging(decimal value);
    partial void OnfrozenBalanceChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void OnmemoChanging(string value);
    partial void OnmemoChanged();
    partial void Onl1Changing(System.Nullable<int> value);
    partial void Onl1Changed();
    partial void Onl2Changing(System.Nullable<int> value);
    partial void Onl2Changed();
    partial void Onl3Changing(System.Nullable<int> value);
    partial void Onl3Changed();
    partial void Onl4Changing(System.Nullable<int> value);
    partial void Onl4Changed();
    partial void Onl5Changing(System.Nullable<int> value);
    partial void Onl5Changed();
    partial void Onl6Changing(System.Nullable<int> value);
    partial void Onl6Changed();
    partial void Onl7Changing(System.Nullable<int> value);
    partial void Onl7Changed();
    partial void Onl8Changing(System.Nullable<int> value);
    partial void Onl8Changed();
    partial void Onl9Changing(System.Nullable<int> value);
    partial void Onl9Changed();
    #endregion
		
		public account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memberId", DbType="Int NOT NULL")]
		public int memberId
		{
			get
			{
				return this._memberId;
			}
			set
			{
				if ((this._memberId != value))
				{
					this.OnmemberIdChanging(value);
					this.SendPropertyChanging();
					this._memberId = value;
					this.SendPropertyChanged("memberId");
					this.OnmemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memberLevelId", DbType="Int NOT NULL")]
		public int memberLevelId
		{
			get
			{
				return this._memberLevelId;
			}
			set
			{
				if ((this._memberLevelId != value))
				{
					this.OnmemberLevelIdChanging(value);
					this.SendPropertyChanging();
					this._memberLevelId = value;
					this.SendPropertyChanged("memberLevelId");
					this.OnmemberLevelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memberParentId", DbType="Int NOT NULL")]
		public int memberParentId
		{
			get
			{
				return this._memberParentId;
			}
			set
			{
				if ((this._memberParentId != value))
				{
					this.OnmemberParentIdChanging(value);
					this.SendPropertyChanging();
					this._memberParentId = value;
					this.SendPropertyChanged("memberParentId");
					this.OnmemberParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string currencyCode
		{
			get
			{
				return this._currencyCode;
			}
			set
			{
				if ((this._currencyCode != value))
				{
					this.OncurrencyCodeChanging(value);
					this.SendPropertyChanging();
					this._currencyCode = value;
					this.SendPropertyChanged("currencyCode");
					this.OncurrencyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="Decimal(28,12) NOT NULL")]
		public decimal balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frozenBalance", DbType="Decimal(28,12) NOT NULL")]
		public decimal frozenBalance
		{
			get
			{
				return this._frozenBalance;
			}
			set
			{
				if ((this._frozenBalance != value))
				{
					this.OnfrozenBalanceChanging(value);
					this.SendPropertyChanging();
					this._frozenBalance = value;
					this.SendPropertyChanged("frozenBalance");
					this.OnfrozenBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memo", DbType="NVarChar(50)")]
		public string memo
		{
			get
			{
				return this._memo;
			}
			set
			{
				if ((this._memo != value))
				{
					this.OnmemoChanging(value);
					this.SendPropertyChanging();
					this._memo = value;
					this.SendPropertyChanged("memo");
					this.OnmemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l1", DbType="Int")]
		public System.Nullable<int> l1
		{
			get
			{
				return this._l1;
			}
			set
			{
				if ((this._l1 != value))
				{
					this.Onl1Changing(value);
					this.SendPropertyChanging();
					this._l1 = value;
					this.SendPropertyChanged("l1");
					this.Onl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l2", DbType="Int")]
		public System.Nullable<int> l2
		{
			get
			{
				return this._l2;
			}
			set
			{
				if ((this._l2 != value))
				{
					this.Onl2Changing(value);
					this.SendPropertyChanging();
					this._l2 = value;
					this.SendPropertyChanged("l2");
					this.Onl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l3", DbType="Int")]
		public System.Nullable<int> l3
		{
			get
			{
				return this._l3;
			}
			set
			{
				if ((this._l3 != value))
				{
					this.Onl3Changing(value);
					this.SendPropertyChanging();
					this._l3 = value;
					this.SendPropertyChanged("l3");
					this.Onl3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l4", DbType="Int")]
		public System.Nullable<int> l4
		{
			get
			{
				return this._l4;
			}
			set
			{
				if ((this._l4 != value))
				{
					this.Onl4Changing(value);
					this.SendPropertyChanging();
					this._l4 = value;
					this.SendPropertyChanged("l4");
					this.Onl4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l5", DbType="Int")]
		public System.Nullable<int> l5
		{
			get
			{
				return this._l5;
			}
			set
			{
				if ((this._l5 != value))
				{
					this.Onl5Changing(value);
					this.SendPropertyChanging();
					this._l5 = value;
					this.SendPropertyChanged("l5");
					this.Onl5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l6", DbType="Int")]
		public System.Nullable<int> l6
		{
			get
			{
				return this._l6;
			}
			set
			{
				if ((this._l6 != value))
				{
					this.Onl6Changing(value);
					this.SendPropertyChanging();
					this._l6 = value;
					this.SendPropertyChanged("l6");
					this.Onl6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l7", DbType="Int")]
		public System.Nullable<int> l7
		{
			get
			{
				return this._l7;
			}
			set
			{
				if ((this._l7 != value))
				{
					this.Onl7Changing(value);
					this.SendPropertyChanging();
					this._l7 = value;
					this.SendPropertyChanged("l7");
					this.Onl7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l8", DbType="Int")]
		public System.Nullable<int> l8
		{
			get
			{
				return this._l8;
			}
			set
			{
				if ((this._l8 != value))
				{
					this.Onl8Changing(value);
					this.SendPropertyChanging();
					this._l8 = value;
					this.SendPropertyChanged("l8");
					this.Onl8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l9", DbType="Int")]
		public System.Nullable<int> l9
		{
			get
			{
				return this._l9;
			}
			set
			{
				if ((this._l9 != value))
				{
					this.Onl9Changing(value);
					this.SendPropertyChanging();
					this._l9 = value;
					this.SendPropertyChanged("l9");
					this.Onl9Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.accountTransDetail")]
	public partial class accountTransDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _transferCateId;
		
		private int _accountIdFrom;
		
		private int _accountIdTo;
		
		private string _currencyCodeFrom;
		
		private string _currencyCodeTo;
		
		private decimal _amountFrom;
		
		private decimal _amountTo;
		
		private decimal _exDiff;
		
		private decimal _fee;
		
		private System.DateTime _createDateTime;
		
		private decimal _exRateWithDiff;
		
		private decimal _exRateWithoutDiff;
		
		private decimal _exRateFrom;
		
		private decimal _exSlopeFrom;
		
		private decimal _exInterceptFrom;
		
		private decimal _exRateTo;
		
		private decimal _exSlopeTo;
		
		private decimal _exInterceptTo;
		
		private decimal _feeRatio;
		
		private decimal _r8;
		
		private decimal _r7;
		
		private decimal _r1;
		
		private System.Nullable<decimal> _amountFromExternal;
		
		private System.Nullable<decimal> _feeRatioInExternal;
		
		private System.Nullable<decimal> _feeRatioOutExternal;
		
		private System.Nullable<decimal> _exRateInExternal;
		
		private System.Nullable<decimal> _exRateOutExternal;
		
		private string _memo;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntransferCateIdChanging(string value);
    partial void OntransferCateIdChanged();
    partial void OnaccountIdFromChanging(int value);
    partial void OnaccountIdFromChanged();
    partial void OnaccountIdToChanging(int value);
    partial void OnaccountIdToChanged();
    partial void OncurrencyCodeFromChanging(string value);
    partial void OncurrencyCodeFromChanged();
    partial void OncurrencyCodeToChanging(string value);
    partial void OncurrencyCodeToChanged();
    partial void OnamountFromChanging(decimal value);
    partial void OnamountFromChanged();
    partial void OnamountToChanging(decimal value);
    partial void OnamountToChanged();
    partial void OnexDiffChanging(decimal value);
    partial void OnexDiffChanged();
    partial void OnfeeChanging(decimal value);
    partial void OnfeeChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void OnexRateWithDiffChanging(decimal value);
    partial void OnexRateWithDiffChanged();
    partial void OnexRateWithoutDiffChanging(decimal value);
    partial void OnexRateWithoutDiffChanged();
    partial void OnexRateFromChanging(decimal value);
    partial void OnexRateFromChanged();
    partial void OnexSlopeFromChanging(decimal value);
    partial void OnexSlopeFromChanged();
    partial void OnexInterceptFromChanging(decimal value);
    partial void OnexInterceptFromChanged();
    partial void OnexRateToChanging(decimal value);
    partial void OnexRateToChanged();
    partial void OnexSlopeToChanging(decimal value);
    partial void OnexSlopeToChanged();
    partial void OnexInterceptToChanging(decimal value);
    partial void OnexInterceptToChanged();
    partial void OnfeeRatioChanging(decimal value);
    partial void OnfeeRatioChanged();
    partial void Onr8Changing(decimal value);
    partial void Onr8Changed();
    partial void Onr7Changing(decimal value);
    partial void Onr7Changed();
    partial void Onr1Changing(decimal value);
    partial void Onr1Changed();
    partial void OnamountFromExternalChanging(System.Nullable<decimal> value);
    partial void OnamountFromExternalChanged();
    partial void OnfeeRatioInExternalChanging(System.Nullable<decimal> value);
    partial void OnfeeRatioInExternalChanged();
    partial void OnfeeRatioOutExternalChanging(System.Nullable<decimal> value);
    partial void OnfeeRatioOutExternalChanged();
    partial void OnexRateInExternalChanging(System.Nullable<decimal> value);
    partial void OnexRateInExternalChanged();
    partial void OnexRateOutExternalChanging(System.Nullable<decimal> value);
    partial void OnexRateOutExternalChanged();
    partial void OnmemoChanging(string value);
    partial void OnmemoChanged();
    #endregion
		
		public accountTransDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transferCateId", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string transferCateId
		{
			get
			{
				return this._transferCateId;
			}
			set
			{
				if ((this._transferCateId != value))
				{
					this.OntransferCateIdChanging(value);
					this.SendPropertyChanging();
					this._transferCateId = value;
					this.SendPropertyChanged("transferCateId");
					this.OntransferCateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accountIdFrom", DbType="Int NOT NULL")]
		public int accountIdFrom
		{
			get
			{
				return this._accountIdFrom;
			}
			set
			{
				if ((this._accountIdFrom != value))
				{
					this.OnaccountIdFromChanging(value);
					this.SendPropertyChanging();
					this._accountIdFrom = value;
					this.SendPropertyChanged("accountIdFrom");
					this.OnaccountIdFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accountIdTo", DbType="Int NOT NULL")]
		public int accountIdTo
		{
			get
			{
				return this._accountIdTo;
			}
			set
			{
				if ((this._accountIdTo != value))
				{
					this.OnaccountIdToChanging(value);
					this.SendPropertyChanging();
					this._accountIdTo = value;
					this.SendPropertyChanged("accountIdTo");
					this.OnaccountIdToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyCodeFrom", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string currencyCodeFrom
		{
			get
			{
				return this._currencyCodeFrom;
			}
			set
			{
				if ((this._currencyCodeFrom != value))
				{
					this.OncurrencyCodeFromChanging(value);
					this.SendPropertyChanging();
					this._currencyCodeFrom = value;
					this.SendPropertyChanged("currencyCodeFrom");
					this.OncurrencyCodeFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyCodeTo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string currencyCodeTo
		{
			get
			{
				return this._currencyCodeTo;
			}
			set
			{
				if ((this._currencyCodeTo != value))
				{
					this.OncurrencyCodeToChanging(value);
					this.SendPropertyChanging();
					this._currencyCodeTo = value;
					this.SendPropertyChanged("currencyCodeTo");
					this.OncurrencyCodeToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountFrom", DbType="Decimal(28,12) NOT NULL")]
		public decimal amountFrom
		{
			get
			{
				return this._amountFrom;
			}
			set
			{
				if ((this._amountFrom != value))
				{
					this.OnamountFromChanging(value);
					this.SendPropertyChanging();
					this._amountFrom = value;
					this.SendPropertyChanged("amountFrom");
					this.OnamountFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountTo", DbType="Decimal(28,12) NOT NULL")]
		public decimal amountTo
		{
			get
			{
				return this._amountTo;
			}
			set
			{
				if ((this._amountTo != value))
				{
					this.OnamountToChanging(value);
					this.SendPropertyChanging();
					this._amountTo = value;
					this.SendPropertyChanged("amountTo");
					this.OnamountToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exDiff", DbType="Decimal(28,12) NOT NULL")]
		public decimal exDiff
		{
			get
			{
				return this._exDiff;
			}
			set
			{
				if ((this._exDiff != value))
				{
					this.OnexDiffChanging(value);
					this.SendPropertyChanging();
					this._exDiff = value;
					this.SendPropertyChanged("exDiff");
					this.OnexDiffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fee", DbType="Decimal(28,12) NOT NULL")]
		public decimal fee
		{
			get
			{
				return this._fee;
			}
			set
			{
				if ((this._fee != value))
				{
					this.OnfeeChanging(value);
					this.SendPropertyChanging();
					this._fee = value;
					this.SendPropertyChanged("fee");
					this.OnfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateWithDiff", DbType="Decimal(28,14) NOT NULL")]
		public decimal exRateWithDiff
		{
			get
			{
				return this._exRateWithDiff;
			}
			set
			{
				if ((this._exRateWithDiff != value))
				{
					this.OnexRateWithDiffChanging(value);
					this.SendPropertyChanging();
					this._exRateWithDiff = value;
					this.SendPropertyChanged("exRateWithDiff");
					this.OnexRateWithDiffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateWithoutDiff", DbType="Decimal(28,14) NOT NULL")]
		public decimal exRateWithoutDiff
		{
			get
			{
				return this._exRateWithoutDiff;
			}
			set
			{
				if ((this._exRateWithoutDiff != value))
				{
					this.OnexRateWithoutDiffChanging(value);
					this.SendPropertyChanging();
					this._exRateWithoutDiff = value;
					this.SendPropertyChanged("exRateWithoutDiff");
					this.OnexRateWithoutDiffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateFrom", DbType="Decimal(16,8) NOT NULL")]
		public decimal exRateFrom
		{
			get
			{
				return this._exRateFrom;
			}
			set
			{
				if ((this._exRateFrom != value))
				{
					this.OnexRateFromChanging(value);
					this.SendPropertyChanging();
					this._exRateFrom = value;
					this.SendPropertyChanged("exRateFrom");
					this.OnexRateFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exSlopeFrom", DbType="Decimal(16,8) NOT NULL")]
		public decimal exSlopeFrom
		{
			get
			{
				return this._exSlopeFrom;
			}
			set
			{
				if ((this._exSlopeFrom != value))
				{
					this.OnexSlopeFromChanging(value);
					this.SendPropertyChanging();
					this._exSlopeFrom = value;
					this.SendPropertyChanged("exSlopeFrom");
					this.OnexSlopeFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exInterceptFrom", DbType="Decimal(24,12) NOT NULL")]
		public decimal exInterceptFrom
		{
			get
			{
				return this._exInterceptFrom;
			}
			set
			{
				if ((this._exInterceptFrom != value))
				{
					this.OnexInterceptFromChanging(value);
					this.SendPropertyChanging();
					this._exInterceptFrom = value;
					this.SendPropertyChanged("exInterceptFrom");
					this.OnexInterceptFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateTo", DbType="Decimal(16,8) NOT NULL")]
		public decimal exRateTo
		{
			get
			{
				return this._exRateTo;
			}
			set
			{
				if ((this._exRateTo != value))
				{
					this.OnexRateToChanging(value);
					this.SendPropertyChanging();
					this._exRateTo = value;
					this.SendPropertyChanged("exRateTo");
					this.OnexRateToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exSlopeTo", DbType="Decimal(16,8) NOT NULL")]
		public decimal exSlopeTo
		{
			get
			{
				return this._exSlopeTo;
			}
			set
			{
				if ((this._exSlopeTo != value))
				{
					this.OnexSlopeToChanging(value);
					this.SendPropertyChanging();
					this._exSlopeTo = value;
					this.SendPropertyChanged("exSlopeTo");
					this.OnexSlopeToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exInterceptTo", DbType="Decimal(24,12) NOT NULL")]
		public decimal exInterceptTo
		{
			get
			{
				return this._exInterceptTo;
			}
			set
			{
				if ((this._exInterceptTo != value))
				{
					this.OnexInterceptToChanging(value);
					this.SendPropertyChanging();
					this._exInterceptTo = value;
					this.SendPropertyChanged("exInterceptTo");
					this.OnexInterceptToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feeRatio", DbType="Decimal(16,8) NOT NULL")]
		public decimal feeRatio
		{
			get
			{
				return this._feeRatio;
			}
			set
			{
				if ((this._feeRatio != value))
				{
					this.OnfeeRatioChanging(value);
					this.SendPropertyChanging();
					this._feeRatio = value;
					this.SendPropertyChanged("feeRatio");
					this.OnfeeRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r8", DbType="Decimal(24,12) NOT NULL")]
		public decimal r8
		{
			get
			{
				return this._r8;
			}
			set
			{
				if ((this._r8 != value))
				{
					this.Onr8Changing(value);
					this.SendPropertyChanging();
					this._r8 = value;
					this.SendPropertyChanged("r8");
					this.Onr8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r7", DbType="Decimal(24,12) NOT NULL")]
		public decimal r7
		{
			get
			{
				return this._r7;
			}
			set
			{
				if ((this._r7 != value))
				{
					this.Onr7Changing(value);
					this.SendPropertyChanging();
					this._r7 = value;
					this.SendPropertyChanged("r7");
					this.Onr7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r1", DbType="Decimal(24,12) NOT NULL")]
		public decimal r1
		{
			get
			{
				return this._r1;
			}
			set
			{
				if ((this._r1 != value))
				{
					this.Onr1Changing(value);
					this.SendPropertyChanging();
					this._r1 = value;
					this.SendPropertyChanged("r1");
					this.Onr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountFromExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> amountFromExternal
		{
			get
			{
				return this._amountFromExternal;
			}
			set
			{
				if ((this._amountFromExternal != value))
				{
					this.OnamountFromExternalChanging(value);
					this.SendPropertyChanging();
					this._amountFromExternal = value;
					this.SendPropertyChanged("amountFromExternal");
					this.OnamountFromExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feeRatioInExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> feeRatioInExternal
		{
			get
			{
				return this._feeRatioInExternal;
			}
			set
			{
				if ((this._feeRatioInExternal != value))
				{
					this.OnfeeRatioInExternalChanging(value);
					this.SendPropertyChanging();
					this._feeRatioInExternal = value;
					this.SendPropertyChanged("feeRatioInExternal");
					this.OnfeeRatioInExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feeRatioOutExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> feeRatioOutExternal
		{
			get
			{
				return this._feeRatioOutExternal;
			}
			set
			{
				if ((this._feeRatioOutExternal != value))
				{
					this.OnfeeRatioOutExternalChanging(value);
					this.SendPropertyChanging();
					this._feeRatioOutExternal = value;
					this.SendPropertyChanged("feeRatioOutExternal");
					this.OnfeeRatioOutExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateInExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> exRateInExternal
		{
			get
			{
				return this._exRateInExternal;
			}
			set
			{
				if ((this._exRateInExternal != value))
				{
					this.OnexRateInExternalChanging(value);
					this.SendPropertyChanging();
					this._exRateInExternal = value;
					this.SendPropertyChanged("exRateInExternal");
					this.OnexRateInExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateOutExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> exRateOutExternal
		{
			get
			{
				return this._exRateOutExternal;
			}
			set
			{
				if ((this._exRateOutExternal != value))
				{
					this.OnexRateOutExternalChanging(value);
					this.SendPropertyChanging();
					this._exRateOutExternal = value;
					this.SendPropertyChanged("exRateOutExternal");
					this.OnexRateOutExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memo", DbType="NVarChar(50)")]
		public string memo
		{
			get
			{
				return this._memo;
			}
			set
			{
				if ((this._memo != value))
				{
					this.OnmemoChanging(value);
					this.SendPropertyChanging();
					this._memo = value;
					this.SendPropertyChanged("memo");
					this.OnmemoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.accountTrans")]
	public partial class accountTrans : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _detailId;
		
		private int _memberId;
		
		private int _memberLevelId;
		
		private int _memberParentId;
		
		private int _accountId;
		
		private string _transferCateId;
		
		private string _transferTypeId;
		
		private string _amountTypeId;
		
		private decimal _amount;
		
		private decimal _balanceBefore;
		
		private decimal _balanceAfter;
		
		private decimal _frozenBalanceBefore;
		
		private decimal _frozenBalanceAfter;
		
		private System.DateTime _createDateTime;
		
		private System.Nullable<int> _l1;
		
		private System.Nullable<int> _l2;
		
		private System.Nullable<int> _l3;
		
		private System.Nullable<int> _l4;
		
		private System.Nullable<int> _l5;
		
		private System.Nullable<int> _l6;
		
		private System.Nullable<int> _l7;
		
		private System.Nullable<int> _l8;
		
		private System.Nullable<int> _l9;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndetailIdChanging(int value);
    partial void OndetailIdChanged();
    partial void OnmemberIdChanging(int value);
    partial void OnmemberIdChanged();
    partial void OnmemberLevelIdChanging(int value);
    partial void OnmemberLevelIdChanged();
    partial void OnmemberParentIdChanging(int value);
    partial void OnmemberParentIdChanged();
    partial void OnaccountIdChanging(int value);
    partial void OnaccountIdChanged();
    partial void OntransferCateIdChanging(string value);
    partial void OntransferCateIdChanged();
    partial void OntransferTypeIdChanging(string value);
    partial void OntransferTypeIdChanged();
    partial void OnamountTypeIdChanging(string value);
    partial void OnamountTypeIdChanged();
    partial void OnamountChanging(decimal value);
    partial void OnamountChanged();
    partial void OnbalanceBeforeChanging(decimal value);
    partial void OnbalanceBeforeChanged();
    partial void OnbalanceAfterChanging(decimal value);
    partial void OnbalanceAfterChanged();
    partial void OnfrozenBalanceBeforeChanging(decimal value);
    partial void OnfrozenBalanceBeforeChanged();
    partial void OnfrozenBalanceAfterChanging(decimal value);
    partial void OnfrozenBalanceAfterChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void Onl1Changing(System.Nullable<int> value);
    partial void Onl1Changed();
    partial void Onl2Changing(System.Nullable<int> value);
    partial void Onl2Changed();
    partial void Onl3Changing(System.Nullable<int> value);
    partial void Onl3Changed();
    partial void Onl4Changing(System.Nullable<int> value);
    partial void Onl4Changed();
    partial void Onl5Changing(System.Nullable<int> value);
    partial void Onl5Changed();
    partial void Onl6Changing(System.Nullable<int> value);
    partial void Onl6Changed();
    partial void Onl7Changing(System.Nullable<int> value);
    partial void Onl7Changed();
    partial void Onl8Changing(System.Nullable<int> value);
    partial void Onl8Changed();
    partial void Onl9Changing(System.Nullable<int> value);
    partial void Onl9Changed();
    #endregion
		
		public accountTrans()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detailId", DbType="Int NOT NULL")]
		public int detailId
		{
			get
			{
				return this._detailId;
			}
			set
			{
				if ((this._detailId != value))
				{
					this.OndetailIdChanging(value);
					this.SendPropertyChanging();
					this._detailId = value;
					this.SendPropertyChanged("detailId");
					this.OndetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memberId", DbType="Int NOT NULL")]
		public int memberId
		{
			get
			{
				return this._memberId;
			}
			set
			{
				if ((this._memberId != value))
				{
					this.OnmemberIdChanging(value);
					this.SendPropertyChanging();
					this._memberId = value;
					this.SendPropertyChanged("memberId");
					this.OnmemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memberLevelId", DbType="Int NOT NULL")]
		public int memberLevelId
		{
			get
			{
				return this._memberLevelId;
			}
			set
			{
				if ((this._memberLevelId != value))
				{
					this.OnmemberLevelIdChanging(value);
					this.SendPropertyChanging();
					this._memberLevelId = value;
					this.SendPropertyChanged("memberLevelId");
					this.OnmemberLevelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memberParentId", DbType="Int NOT NULL")]
		public int memberParentId
		{
			get
			{
				return this._memberParentId;
			}
			set
			{
				if ((this._memberParentId != value))
				{
					this.OnmemberParentIdChanging(value);
					this.SendPropertyChanging();
					this._memberParentId = value;
					this.SendPropertyChanged("memberParentId");
					this.OnmemberParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accountId", DbType="Int NOT NULL")]
		public int accountId
		{
			get
			{
				return this._accountId;
			}
			set
			{
				if ((this._accountId != value))
				{
					this.OnaccountIdChanging(value);
					this.SendPropertyChanging();
					this._accountId = value;
					this.SendPropertyChanged("accountId");
					this.OnaccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transferCateId", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string transferCateId
		{
			get
			{
				return this._transferCateId;
			}
			set
			{
				if ((this._transferCateId != value))
				{
					this.OntransferCateIdChanging(value);
					this.SendPropertyChanging();
					this._transferCateId = value;
					this.SendPropertyChanged("transferCateId");
					this.OntransferCateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transferTypeId", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string transferTypeId
		{
			get
			{
				return this._transferTypeId;
			}
			set
			{
				if ((this._transferTypeId != value))
				{
					this.OntransferTypeIdChanging(value);
					this.SendPropertyChanging();
					this._transferTypeId = value;
					this.SendPropertyChanged("transferTypeId");
					this.OntransferTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountTypeId", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string amountTypeId
		{
			get
			{
				return this._amountTypeId;
			}
			set
			{
				if ((this._amountTypeId != value))
				{
					this.OnamountTypeIdChanging(value);
					this.SendPropertyChanging();
					this._amountTypeId = value;
					this.SendPropertyChanged("amountTypeId");
					this.OnamountTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(28,12) NOT NULL")]
		public decimal amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balanceBefore", DbType="Decimal(28,12) NOT NULL")]
		public decimal balanceBefore
		{
			get
			{
				return this._balanceBefore;
			}
			set
			{
				if ((this._balanceBefore != value))
				{
					this.OnbalanceBeforeChanging(value);
					this.SendPropertyChanging();
					this._balanceBefore = value;
					this.SendPropertyChanged("balanceBefore");
					this.OnbalanceBeforeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balanceAfter", DbType="Decimal(28,12) NOT NULL")]
		public decimal balanceAfter
		{
			get
			{
				return this._balanceAfter;
			}
			set
			{
				if ((this._balanceAfter != value))
				{
					this.OnbalanceAfterChanging(value);
					this.SendPropertyChanging();
					this._balanceAfter = value;
					this.SendPropertyChanged("balanceAfter");
					this.OnbalanceAfterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frozenBalanceBefore", DbType="Decimal(28,12) NOT NULL")]
		public decimal frozenBalanceBefore
		{
			get
			{
				return this._frozenBalanceBefore;
			}
			set
			{
				if ((this._frozenBalanceBefore != value))
				{
					this.OnfrozenBalanceBeforeChanging(value);
					this.SendPropertyChanging();
					this._frozenBalanceBefore = value;
					this.SendPropertyChanged("frozenBalanceBefore");
					this.OnfrozenBalanceBeforeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frozenBalanceAfter", DbType="Decimal(28,12) NOT NULL")]
		public decimal frozenBalanceAfter
		{
			get
			{
				return this._frozenBalanceAfter;
			}
			set
			{
				if ((this._frozenBalanceAfter != value))
				{
					this.OnfrozenBalanceAfterChanging(value);
					this.SendPropertyChanging();
					this._frozenBalanceAfter = value;
					this.SendPropertyChanged("frozenBalanceAfter");
					this.OnfrozenBalanceAfterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l1", DbType="Int")]
		public System.Nullable<int> l1
		{
			get
			{
				return this._l1;
			}
			set
			{
				if ((this._l1 != value))
				{
					this.Onl1Changing(value);
					this.SendPropertyChanging();
					this._l1 = value;
					this.SendPropertyChanged("l1");
					this.Onl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l2", DbType="Int")]
		public System.Nullable<int> l2
		{
			get
			{
				return this._l2;
			}
			set
			{
				if ((this._l2 != value))
				{
					this.Onl2Changing(value);
					this.SendPropertyChanging();
					this._l2 = value;
					this.SendPropertyChanged("l2");
					this.Onl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l3", DbType="Int")]
		public System.Nullable<int> l3
		{
			get
			{
				return this._l3;
			}
			set
			{
				if ((this._l3 != value))
				{
					this.Onl3Changing(value);
					this.SendPropertyChanging();
					this._l3 = value;
					this.SendPropertyChanged("l3");
					this.Onl3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l4", DbType="Int")]
		public System.Nullable<int> l4
		{
			get
			{
				return this._l4;
			}
			set
			{
				if ((this._l4 != value))
				{
					this.Onl4Changing(value);
					this.SendPropertyChanging();
					this._l4 = value;
					this.SendPropertyChanged("l4");
					this.Onl4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l5", DbType="Int")]
		public System.Nullable<int> l5
		{
			get
			{
				return this._l5;
			}
			set
			{
				if ((this._l5 != value))
				{
					this.Onl5Changing(value);
					this.SendPropertyChanging();
					this._l5 = value;
					this.SendPropertyChanged("l5");
					this.Onl5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l6", DbType="Int")]
		public System.Nullable<int> l6
		{
			get
			{
				return this._l6;
			}
			set
			{
				if ((this._l6 != value))
				{
					this.Onl6Changing(value);
					this.SendPropertyChanging();
					this._l6 = value;
					this.SendPropertyChanged("l6");
					this.Onl6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l7", DbType="Int")]
		public System.Nullable<int> l7
		{
			get
			{
				return this._l7;
			}
			set
			{
				if ((this._l7 != value))
				{
					this.Onl7Changing(value);
					this.SendPropertyChanging();
					this._l7 = value;
					this.SendPropertyChanged("l7");
					this.Onl7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l8", DbType="Int")]
		public System.Nullable<int> l8
		{
			get
			{
				return this._l8;
			}
			set
			{
				if ((this._l8 != value))
				{
					this.Onl8Changing(value);
					this.SendPropertyChanging();
					this._l8 = value;
					this.SendPropertyChanged("l8");
					this.Onl8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l9", DbType="Int")]
		public System.Nullable<int> l9
		{
			get
			{
				return this._l9;
			}
			set
			{
				if ((this._l9 != value))
				{
					this.Onl9Changing(value);
					this.SendPropertyChanging();
					this._l9 = value;
					this.SendPropertyChanged("l9");
					this.Onl9Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.withdrawalOrder")]
	public partial class withdrawalOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _accountIdFrom;
		
		private int _bankAccountIdTo;
		
		private string _currencyCodeFrom;
		
		private string _currencyCodeTo;
		
		private decimal _amountFrom;
		
		private decimal _amountTo;
		
		private decimal _exDiff;
		
		private decimal _fee;
		
		private System.DateTime _createDateTime;
		
		private decimal _exRateWithDiff;
		
		private decimal _exRateWithoutDiff;
		
		private decimal _exRateFrom;
		
		private decimal _exSlopeFrom;
		
		private decimal _exInterceptFrom;
		
		private decimal _exRateTo;
		
		private decimal _exSlopeTo;
		
		private decimal _exInterceptTo;
		
		private decimal _feeRatio;
		
		private System.Nullable<decimal> _r8;
		
		private System.Nullable<decimal> _r7;
		
		private System.Nullable<decimal> _r1;
		
		private System.Nullable<decimal> _amountFromExternal;
		
		private System.Nullable<decimal> _feeRatioInExternal;
		
		private System.Nullable<decimal> _feeRatioOutExternal;
		
		private System.Nullable<decimal> _exRateInExternal;
		
		private System.Nullable<decimal> _exRateOutExternal;
		
		private bool _isApiCreate;
		
		private string _status;
		
		private string _memo;
		
		private int _memberId;
		
		private decimal _p8;
		
		private decimal _p7;
		
		private string _feeMode;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaccountIdFromChanging(int value);
    partial void OnaccountIdFromChanged();
    partial void OnbankAccountIdToChanging(int value);
    partial void OnbankAccountIdToChanged();
    partial void OncurrencyCodeFromChanging(string value);
    partial void OncurrencyCodeFromChanged();
    partial void OncurrencyCodeToChanging(string value);
    partial void OncurrencyCodeToChanged();
    partial void OnamountFromChanging(decimal value);
    partial void OnamountFromChanged();
    partial void OnamountToChanging(decimal value);
    partial void OnamountToChanged();
    partial void OnexDiffChanging(decimal value);
    partial void OnexDiffChanged();
    partial void OnfeeChanging(decimal value);
    partial void OnfeeChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void OnexRateWithDiffChanging(decimal value);
    partial void OnexRateWithDiffChanged();
    partial void OnexRateWithoutDiffChanging(decimal value);
    partial void OnexRateWithoutDiffChanged();
    partial void OnexRateFromChanging(decimal value);
    partial void OnexRateFromChanged();
    partial void OnexSlopeFromChanging(decimal value);
    partial void OnexSlopeFromChanged();
    partial void OnexInterceptFromChanging(decimal value);
    partial void OnexInterceptFromChanged();
    partial void OnexRateToChanging(decimal value);
    partial void OnexRateToChanged();
    partial void OnexSlopeToChanging(decimal value);
    partial void OnexSlopeToChanged();
    partial void OnexInterceptToChanging(decimal value);
    partial void OnexInterceptToChanged();
    partial void OnfeeRatioChanging(decimal value);
    partial void OnfeeRatioChanged();
    partial void Onr8Changing(System.Nullable<decimal> value);
    partial void Onr8Changed();
    partial void Onr7Changing(System.Nullable<decimal> value);
    partial void Onr7Changed();
    partial void Onr1Changing(System.Nullable<decimal> value);
    partial void Onr1Changed();
    partial void OnamountFromExternalChanging(System.Nullable<decimal> value);
    partial void OnamountFromExternalChanged();
    partial void OnfeeRatioInExternalChanging(System.Nullable<decimal> value);
    partial void OnfeeRatioInExternalChanged();
    partial void OnfeeRatioOutExternalChanging(System.Nullable<decimal> value);
    partial void OnfeeRatioOutExternalChanged();
    partial void OnexRateInExternalChanging(System.Nullable<decimal> value);
    partial void OnexRateInExternalChanged();
    partial void OnexRateOutExternalChanging(System.Nullable<decimal> value);
    partial void OnexRateOutExternalChanged();
    partial void OnisApiCreateChanging(bool value);
    partial void OnisApiCreateChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnmemoChanging(string value);
    partial void OnmemoChanged();
    partial void OnmemberIdChanging(int value);
    partial void OnmemberIdChanged();
    partial void Onp8Changing(decimal value);
    partial void Onp8Changed();
    partial void Onp7Changing(decimal value);
    partial void Onp7Changed();
    partial void OnfeeModeChanging(string value);
    partial void OnfeeModeChanged();
    #endregion
		
		public withdrawalOrder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accountIdFrom", DbType="Int NOT NULL")]
		public int accountIdFrom
		{
			get
			{
				return this._accountIdFrom;
			}
			set
			{
				if ((this._accountIdFrom != value))
				{
					this.OnaccountIdFromChanging(value);
					this.SendPropertyChanging();
					this._accountIdFrom = value;
					this.SendPropertyChanged("accountIdFrom");
					this.OnaccountIdFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankAccountIdTo", DbType="Int NOT NULL")]
		public int bankAccountIdTo
		{
			get
			{
				return this._bankAccountIdTo;
			}
			set
			{
				if ((this._bankAccountIdTo != value))
				{
					this.OnbankAccountIdToChanging(value);
					this.SendPropertyChanging();
					this._bankAccountIdTo = value;
					this.SendPropertyChanged("bankAccountIdTo");
					this.OnbankAccountIdToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyCodeFrom", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string currencyCodeFrom
		{
			get
			{
				return this._currencyCodeFrom;
			}
			set
			{
				if ((this._currencyCodeFrom != value))
				{
					this.OncurrencyCodeFromChanging(value);
					this.SendPropertyChanging();
					this._currencyCodeFrom = value;
					this.SendPropertyChanged("currencyCodeFrom");
					this.OncurrencyCodeFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyCodeTo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string currencyCodeTo
		{
			get
			{
				return this._currencyCodeTo;
			}
			set
			{
				if ((this._currencyCodeTo != value))
				{
					this.OncurrencyCodeToChanging(value);
					this.SendPropertyChanging();
					this._currencyCodeTo = value;
					this.SendPropertyChanged("currencyCodeTo");
					this.OncurrencyCodeToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountFrom", DbType="Decimal(28,12) NOT NULL")]
		public decimal amountFrom
		{
			get
			{
				return this._amountFrom;
			}
			set
			{
				if ((this._amountFrom != value))
				{
					this.OnamountFromChanging(value);
					this.SendPropertyChanging();
					this._amountFrom = value;
					this.SendPropertyChanged("amountFrom");
					this.OnamountFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountTo", DbType="Decimal(28,12) NOT NULL")]
		public decimal amountTo
		{
			get
			{
				return this._amountTo;
			}
			set
			{
				if ((this._amountTo != value))
				{
					this.OnamountToChanging(value);
					this.SendPropertyChanging();
					this._amountTo = value;
					this.SendPropertyChanged("amountTo");
					this.OnamountToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exDiff", DbType="Decimal(28,12) NOT NULL")]
		public decimal exDiff
		{
			get
			{
				return this._exDiff;
			}
			set
			{
				if ((this._exDiff != value))
				{
					this.OnexDiffChanging(value);
					this.SendPropertyChanging();
					this._exDiff = value;
					this.SendPropertyChanged("exDiff");
					this.OnexDiffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fee", DbType="Decimal(28,12) NOT NULL")]
		public decimal fee
		{
			get
			{
				return this._fee;
			}
			set
			{
				if ((this._fee != value))
				{
					this.OnfeeChanging(value);
					this.SendPropertyChanging();
					this._fee = value;
					this.SendPropertyChanged("fee");
					this.OnfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateWithDiff", DbType="Decimal(28,14) NOT NULL")]
		public decimal exRateWithDiff
		{
			get
			{
				return this._exRateWithDiff;
			}
			set
			{
				if ((this._exRateWithDiff != value))
				{
					this.OnexRateWithDiffChanging(value);
					this.SendPropertyChanging();
					this._exRateWithDiff = value;
					this.SendPropertyChanged("exRateWithDiff");
					this.OnexRateWithDiffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateWithoutDiff", DbType="Decimal(28,14) NOT NULL")]
		public decimal exRateWithoutDiff
		{
			get
			{
				return this._exRateWithoutDiff;
			}
			set
			{
				if ((this._exRateWithoutDiff != value))
				{
					this.OnexRateWithoutDiffChanging(value);
					this.SendPropertyChanging();
					this._exRateWithoutDiff = value;
					this.SendPropertyChanged("exRateWithoutDiff");
					this.OnexRateWithoutDiffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateFrom", DbType="Decimal(16,8) NOT NULL")]
		public decimal exRateFrom
		{
			get
			{
				return this._exRateFrom;
			}
			set
			{
				if ((this._exRateFrom != value))
				{
					this.OnexRateFromChanging(value);
					this.SendPropertyChanging();
					this._exRateFrom = value;
					this.SendPropertyChanged("exRateFrom");
					this.OnexRateFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exSlopeFrom", DbType="Decimal(16,8) NOT NULL")]
		public decimal exSlopeFrom
		{
			get
			{
				return this._exSlopeFrom;
			}
			set
			{
				if ((this._exSlopeFrom != value))
				{
					this.OnexSlopeFromChanging(value);
					this.SendPropertyChanging();
					this._exSlopeFrom = value;
					this.SendPropertyChanged("exSlopeFrom");
					this.OnexSlopeFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exInterceptFrom", DbType="Decimal(24,12) NOT NULL")]
		public decimal exInterceptFrom
		{
			get
			{
				return this._exInterceptFrom;
			}
			set
			{
				if ((this._exInterceptFrom != value))
				{
					this.OnexInterceptFromChanging(value);
					this.SendPropertyChanging();
					this._exInterceptFrom = value;
					this.SendPropertyChanged("exInterceptFrom");
					this.OnexInterceptFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateTo", DbType="Decimal(16,8) NOT NULL")]
		public decimal exRateTo
		{
			get
			{
				return this._exRateTo;
			}
			set
			{
				if ((this._exRateTo != value))
				{
					this.OnexRateToChanging(value);
					this.SendPropertyChanging();
					this._exRateTo = value;
					this.SendPropertyChanged("exRateTo");
					this.OnexRateToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exSlopeTo", DbType="Decimal(16,8) NOT NULL")]
		public decimal exSlopeTo
		{
			get
			{
				return this._exSlopeTo;
			}
			set
			{
				if ((this._exSlopeTo != value))
				{
					this.OnexSlopeToChanging(value);
					this.SendPropertyChanging();
					this._exSlopeTo = value;
					this.SendPropertyChanged("exSlopeTo");
					this.OnexSlopeToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exInterceptTo", DbType="Decimal(24,12) NOT NULL")]
		public decimal exInterceptTo
		{
			get
			{
				return this._exInterceptTo;
			}
			set
			{
				if ((this._exInterceptTo != value))
				{
					this.OnexInterceptToChanging(value);
					this.SendPropertyChanging();
					this._exInterceptTo = value;
					this.SendPropertyChanged("exInterceptTo");
					this.OnexInterceptToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feeRatio", DbType="Decimal(16,8) NOT NULL")]
		public decimal feeRatio
		{
			get
			{
				return this._feeRatio;
			}
			set
			{
				if ((this._feeRatio != value))
				{
					this.OnfeeRatioChanging(value);
					this.SendPropertyChanging();
					this._feeRatio = value;
					this.SendPropertyChanged("feeRatio");
					this.OnfeeRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r8", DbType="Decimal(24,12)")]
		public System.Nullable<decimal> r8
		{
			get
			{
				return this._r8;
			}
			set
			{
				if ((this._r8 != value))
				{
					this.Onr8Changing(value);
					this.SendPropertyChanging();
					this._r8 = value;
					this.SendPropertyChanged("r8");
					this.Onr8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r7", DbType="Decimal(24,12)")]
		public System.Nullable<decimal> r7
		{
			get
			{
				return this._r7;
			}
			set
			{
				if ((this._r7 != value))
				{
					this.Onr7Changing(value);
					this.SendPropertyChanging();
					this._r7 = value;
					this.SendPropertyChanged("r7");
					this.Onr7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r1", DbType="Decimal(24,12)")]
		public System.Nullable<decimal> r1
		{
			get
			{
				return this._r1;
			}
			set
			{
				if ((this._r1 != value))
				{
					this.Onr1Changing(value);
					this.SendPropertyChanging();
					this._r1 = value;
					this.SendPropertyChanged("r1");
					this.Onr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountFromExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> amountFromExternal
		{
			get
			{
				return this._amountFromExternal;
			}
			set
			{
				if ((this._amountFromExternal != value))
				{
					this.OnamountFromExternalChanging(value);
					this.SendPropertyChanging();
					this._amountFromExternal = value;
					this.SendPropertyChanged("amountFromExternal");
					this.OnamountFromExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feeRatioInExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> feeRatioInExternal
		{
			get
			{
				return this._feeRatioInExternal;
			}
			set
			{
				if ((this._feeRatioInExternal != value))
				{
					this.OnfeeRatioInExternalChanging(value);
					this.SendPropertyChanging();
					this._feeRatioInExternal = value;
					this.SendPropertyChanged("feeRatioInExternal");
					this.OnfeeRatioInExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feeRatioOutExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> feeRatioOutExternal
		{
			get
			{
				return this._feeRatioOutExternal;
			}
			set
			{
				if ((this._feeRatioOutExternal != value))
				{
					this.OnfeeRatioOutExternalChanging(value);
					this.SendPropertyChanging();
					this._feeRatioOutExternal = value;
					this.SendPropertyChanged("feeRatioOutExternal");
					this.OnfeeRatioOutExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateInExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> exRateInExternal
		{
			get
			{
				return this._exRateInExternal;
			}
			set
			{
				if ((this._exRateInExternal != value))
				{
					this.OnexRateInExternalChanging(value);
					this.SendPropertyChanging();
					this._exRateInExternal = value;
					this.SendPropertyChanged("exRateInExternal");
					this.OnexRateInExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRateOutExternal", DbType="Decimal(28,12)")]
		public System.Nullable<decimal> exRateOutExternal
		{
			get
			{
				return this._exRateOutExternal;
			}
			set
			{
				if ((this._exRateOutExternal != value))
				{
					this.OnexRateOutExternalChanging(value);
					this.SendPropertyChanging();
					this._exRateOutExternal = value;
					this.SendPropertyChanged("exRateOutExternal");
					this.OnexRateOutExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isApiCreate", DbType="Bit NOT NULL")]
		public bool isApiCreate
		{
			get
			{
				return this._isApiCreate;
			}
			set
			{
				if ((this._isApiCreate != value))
				{
					this.OnisApiCreateChanging(value);
					this.SendPropertyChanging();
					this._isApiCreate = value;
					this.SendPropertyChanged("isApiCreate");
					this.OnisApiCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memo", DbType="NVarChar(50)")]
		public string memo
		{
			get
			{
				return this._memo;
			}
			set
			{
				if ((this._memo != value))
				{
					this.OnmemoChanging(value);
					this.SendPropertyChanging();
					this._memo = value;
					this.SendPropertyChanged("memo");
					this.OnmemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memberId", DbType="Int NOT NULL")]
		public int memberId
		{
			get
			{
				return this._memberId;
			}
			set
			{
				if ((this._memberId != value))
				{
					this.OnmemberIdChanging(value);
					this.SendPropertyChanging();
					this._memberId = value;
					this.SendPropertyChanged("memberId");
					this.OnmemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p8", DbType="Decimal(24,12) NOT NULL")]
		public decimal p8
		{
			get
			{
				return this._p8;
			}
			set
			{
				if ((this._p8 != value))
				{
					this.Onp8Changing(value);
					this.SendPropertyChanging();
					this._p8 = value;
					this.SendPropertyChanged("p8");
					this.Onp8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p7", DbType="Decimal(24,12) NOT NULL")]
		public decimal p7
		{
			get
			{
				return this._p7;
			}
			set
			{
				if ((this._p7 != value))
				{
					this.Onp7Changing(value);
					this.SendPropertyChanging();
					this._p7 = value;
					this.SendPropertyChanged("p7");
					this.Onp7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feeMode", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string feeMode
		{
			get
			{
				return this._feeMode;
			}
			set
			{
				if ((this._feeMode != value))
				{
					this.OnfeeModeChanging(value);
					this.SendPropertyChanging();
					this._feeMode = value;
					this.SendPropertyChanged("feeMode");
					this.OnfeeModeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
