#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAccountRegister
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bitject")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertbankAccount(bankAccount instance);
    partial void UpdatebankAccount(bankAccount instance);
    partial void DeletebankAccount(bankAccount instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::BankAccountRegister.Properties.Settings.Default.bitjectConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bankAccount> bankAccount
		{
			get
			{
				return this.GetTable<bankAccount>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bankAccount")]
	public partial class bankAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _memberId;
		
		private int _parentId;
		
		private string _bankId;
		
		private string _bankBranchName;
		
		private string _chinaMainRegionId;
		
		private string _chinaSubRegionId;
		
		private string _bankAccountNumber;
		
		private string _currencyCode;
		
		private decimal _amount;
		
		private string _status;
		
		private bool _isChecked;
		
		private System.DateTime _createDateTime;
		
		private string _memo;
		
		private System.Nullable<int> _l1;
		
		private System.Nullable<int> _l2;
		
		private System.Nullable<int> _l3;
		
		private System.Nullable<int> _l4;
		
		private System.Nullable<int> _l5;
		
		private System.Nullable<int> _l6;
		
		private System.Nullable<int> _l7;
		
		private System.Nullable<int> _l8;
		
		private System.Nullable<int> _l9;
		
		private System.Nullable<System.DateTime> _lastModifyDateTime;
		
		private System.Nullable<int> _lastModifierId;
		
		private string _registerStatus;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmemberIdChanging(int value);
    partial void OnmemberIdChanged();
    partial void OnparentIdChanging(int value);
    partial void OnparentIdChanged();
    partial void OnbankIdChanging(string value);
    partial void OnbankIdChanged();
    partial void OnbankBranchNameChanging(string value);
    partial void OnbankBranchNameChanged();
    partial void OnchinaMainRegionIdChanging(string value);
    partial void OnchinaMainRegionIdChanged();
    partial void OnchinaSubRegionIdChanging(string value);
    partial void OnchinaSubRegionIdChanged();
    partial void OnbankAccountNumberChanging(string value);
    partial void OnbankAccountNumberChanged();
    partial void OncurrencyCodeChanging(string value);
    partial void OncurrencyCodeChanged();
    partial void OnamountChanging(decimal value);
    partial void OnamountChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnisCheckedChanging(bool value);
    partial void OnisCheckedChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void OnmemoChanging(string value);
    partial void OnmemoChanged();
    partial void Onl1Changing(System.Nullable<int> value);
    partial void Onl1Changed();
    partial void Onl2Changing(System.Nullable<int> value);
    partial void Onl2Changed();
    partial void Onl3Changing(System.Nullable<int> value);
    partial void Onl3Changed();
    partial void Onl4Changing(System.Nullable<int> value);
    partial void Onl4Changed();
    partial void Onl5Changing(System.Nullable<int> value);
    partial void Onl5Changed();
    partial void Onl6Changing(System.Nullable<int> value);
    partial void Onl6Changed();
    partial void Onl7Changing(System.Nullable<int> value);
    partial void Onl7Changed();
    partial void Onl8Changing(System.Nullable<int> value);
    partial void Onl8Changed();
    partial void Onl9Changing(System.Nullable<int> value);
    partial void Onl9Changed();
    partial void OnlastModifyDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastModifyDateTimeChanged();
    partial void OnlastModifierIdChanging(System.Nullable<int> value);
    partial void OnlastModifierIdChanged();
    partial void OnregisterStatusChanging(string value);
    partial void OnregisterStatusChanged();
    #endregion
		
		public bankAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memberId", DbType="Int NOT NULL")]
		public int memberId
		{
			get
			{
				return this._memberId;
			}
			set
			{
				if ((this._memberId != value))
				{
					this.OnmemberIdChanging(value);
					this.SendPropertyChanging();
					this._memberId = value;
					this.SendPropertyChanged("memberId");
					this.OnmemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentId", DbType="Int NOT NULL")]
		public int parentId
		{
			get
			{
				return this._parentId;
			}
			set
			{
				if ((this._parentId != value))
				{
					this.OnparentIdChanging(value);
					this.SendPropertyChanging();
					this._parentId = value;
					this.SendPropertyChanged("parentId");
					this.OnparentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankId", DbType="VarChar(10)")]
		public string bankId
		{
			get
			{
				return this._bankId;
			}
			set
			{
				if ((this._bankId != value))
				{
					this.OnbankIdChanging(value);
					this.SendPropertyChanging();
					this._bankId = value;
					this.SendPropertyChanged("bankId");
					this.OnbankIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankBranchName", DbType="NVarChar(30)")]
		public string bankBranchName
		{
			get
			{
				return this._bankBranchName;
			}
			set
			{
				if ((this._bankBranchName != value))
				{
					this.OnbankBranchNameChanging(value);
					this.SendPropertyChanging();
					this._bankBranchName = value;
					this.SendPropertyChanged("bankBranchName");
					this.OnbankBranchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chinaMainRegionId", DbType="VarChar(30)")]
		public string chinaMainRegionId
		{
			get
			{
				return this._chinaMainRegionId;
			}
			set
			{
				if ((this._chinaMainRegionId != value))
				{
					this.OnchinaMainRegionIdChanging(value);
					this.SendPropertyChanging();
					this._chinaMainRegionId = value;
					this.SendPropertyChanged("chinaMainRegionId");
					this.OnchinaMainRegionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chinaSubRegionId", DbType="VarChar(30)")]
		public string chinaSubRegionId
		{
			get
			{
				return this._chinaSubRegionId;
			}
			set
			{
				if ((this._chinaSubRegionId != value))
				{
					this.OnchinaSubRegionIdChanging(value);
					this.SendPropertyChanging();
					this._chinaSubRegionId = value;
					this.SendPropertyChanged("chinaSubRegionId");
					this.OnchinaSubRegionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankAccountNumber", DbType="VarChar(30)")]
		public string bankAccountNumber
		{
			get
			{
				return this._bankAccountNumber;
			}
			set
			{
				if ((this._bankAccountNumber != value))
				{
					this.OnbankAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._bankAccountNumber = value;
					this.SendPropertyChanged("bankAccountNumber");
					this.OnbankAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string currencyCode
		{
			get
			{
				return this._currencyCode;
			}
			set
			{
				if ((this._currencyCode != value))
				{
					this.OncurrencyCodeChanging(value);
					this.SendPropertyChanging();
					this._currencyCode = value;
					this.SendPropertyChanged("currencyCode");
					this.OncurrencyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(28,12) NOT NULL")]
		public decimal amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isChecked", DbType="Bit NOT NULL")]
		public bool isChecked
		{
			get
			{
				return this._isChecked;
			}
			set
			{
				if ((this._isChecked != value))
				{
					this.OnisCheckedChanging(value);
					this.SendPropertyChanging();
					this._isChecked = value;
					this.SendPropertyChanged("isChecked");
					this.OnisCheckedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memo", DbType="NVarChar(50)")]
		public string memo
		{
			get
			{
				return this._memo;
			}
			set
			{
				if ((this._memo != value))
				{
					this.OnmemoChanging(value);
					this.SendPropertyChanging();
					this._memo = value;
					this.SendPropertyChanged("memo");
					this.OnmemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l1", DbType="Int")]
		public System.Nullable<int> l1
		{
			get
			{
				return this._l1;
			}
			set
			{
				if ((this._l1 != value))
				{
					this.Onl1Changing(value);
					this.SendPropertyChanging();
					this._l1 = value;
					this.SendPropertyChanged("l1");
					this.Onl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l2", DbType="Int")]
		public System.Nullable<int> l2
		{
			get
			{
				return this._l2;
			}
			set
			{
				if ((this._l2 != value))
				{
					this.Onl2Changing(value);
					this.SendPropertyChanging();
					this._l2 = value;
					this.SendPropertyChanged("l2");
					this.Onl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l3", DbType="Int")]
		public System.Nullable<int> l3
		{
			get
			{
				return this._l3;
			}
			set
			{
				if ((this._l3 != value))
				{
					this.Onl3Changing(value);
					this.SendPropertyChanging();
					this._l3 = value;
					this.SendPropertyChanged("l3");
					this.Onl3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l4", DbType="Int")]
		public System.Nullable<int> l4
		{
			get
			{
				return this._l4;
			}
			set
			{
				if ((this._l4 != value))
				{
					this.Onl4Changing(value);
					this.SendPropertyChanging();
					this._l4 = value;
					this.SendPropertyChanged("l4");
					this.Onl4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l5", DbType="Int")]
		public System.Nullable<int> l5
		{
			get
			{
				return this._l5;
			}
			set
			{
				if ((this._l5 != value))
				{
					this.Onl5Changing(value);
					this.SendPropertyChanging();
					this._l5 = value;
					this.SendPropertyChanged("l5");
					this.Onl5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l6", DbType="Int")]
		public System.Nullable<int> l6
		{
			get
			{
				return this._l6;
			}
			set
			{
				if ((this._l6 != value))
				{
					this.Onl6Changing(value);
					this.SendPropertyChanging();
					this._l6 = value;
					this.SendPropertyChanged("l6");
					this.Onl6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l7", DbType="Int")]
		public System.Nullable<int> l7
		{
			get
			{
				return this._l7;
			}
			set
			{
				if ((this._l7 != value))
				{
					this.Onl7Changing(value);
					this.SendPropertyChanging();
					this._l7 = value;
					this.SendPropertyChanged("l7");
					this.Onl7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l8", DbType="Int")]
		public System.Nullable<int> l8
		{
			get
			{
				return this._l8;
			}
			set
			{
				if ((this._l8 != value))
				{
					this.Onl8Changing(value);
					this.SendPropertyChanging();
					this._l8 = value;
					this.SendPropertyChanged("l8");
					this.Onl8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l9", DbType="Int")]
		public System.Nullable<int> l9
		{
			get
			{
				return this._l9;
			}
			set
			{
				if ((this._l9 != value))
				{
					this.Onl9Changing(value);
					this.SendPropertyChanging();
					this._l9 = value;
					this.SendPropertyChanged("l9");
					this.Onl9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastModifyDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastModifyDateTime
		{
			get
			{
				return this._lastModifyDateTime;
			}
			set
			{
				if ((this._lastModifyDateTime != value))
				{
					this.OnlastModifyDateTimeChanging(value);
					this.SendPropertyChanging();
					this._lastModifyDateTime = value;
					this.SendPropertyChanged("lastModifyDateTime");
					this.OnlastModifyDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastModifierId", DbType="Int")]
		public System.Nullable<int> lastModifierId
		{
			get
			{
				return this._lastModifierId;
			}
			set
			{
				if ((this._lastModifierId != value))
				{
					this.OnlastModifierIdChanging(value);
					this.SendPropertyChanging();
					this._lastModifierId = value;
					this.SendPropertyChanged("lastModifierId");
					this.OnlastModifierIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registerStatus", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string registerStatus
		{
			get
			{
				return this._registerStatus;
			}
			set
			{
				if ((this._registerStatus != value))
				{
					this.OnregisterStatusChanging(value);
					this.SendPropertyChanging();
					this._registerStatus = value;
					this.SendPropertyChanged("registerStatus");
					this.OnregisterStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
